version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_PASSWORD}}
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
