system-ghc: true
install-ghc: false
resolver: lts-22.39
packages: []
extra-deps:
- weeder-2.10.0
- stan-0.2.0.0
# Extra deps for stan
- ansi-wl-pprint-0.6.9
- dir-traverse-0.2.3.0
- extensions-0.1.0.1
- optparse-applicative-0.17.1.0
- tomland-1.3.3.3
- trial-0.0.0.0
- trial-optparse-applicative-0.0.0.0
- trial-tomland-0.0.0.0
- validation-selective-0.2.0.0
